import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import {resolveEnchantRows,sumEnchantRows} from "../lib/enchant-core.mjs";
const base=JSON.parse(fs.readFileSync(new URL("../data/enchants.json",import.meta.url),"utf8"));
const series=JSON.parse(fs.readFileSync(new URL("../data/enchant-series.json",import.meta.url),"utf8"));
const expanded=series.flatMap(group=>group.entries.map(([name,value],index)=>({id:`${group.id}-${index+1}`,name,attribute:group.attribute,value,unit:group.unit})));
const rows=[...base,...expanded.filter(row=>!base.some(existing=>existing.name===row.name&&existing.attribute===row.attribute))];
test("çift efsunlu eşya adını iki bağımsız özelliğe çözer",()=>{const found=resolveEnchantRows("Alaska Modeli Bolat Modeli Kolye",rows);assert.deepEqual(found.map(x=>x.name).toSorted(),["Alaska Modeli","Bolat Modeli"]);assert.deepEqual(sumEnchantRows(found),{"Büyü Hasarı (Buz)":130000,"Büyü Hasarı (Elektrik)":130000})});
test("bilinmeyen eşya adına tahmini efsun üretmez",()=>assert.deepEqual(resolveEnchantRows("Bilinmeyen Deneme Yüzüğü",rows),[]));
test("alt kademe efsunları da çözer",()=>{const found=resolveEnchantRows("Erciyes Modeli Plastik Emsali Gözlük",rows);assert.deepEqual(sumEnchantRows(found),{"Büyü Hasarı (Buz)":9000,"Direnç (Elektrik)":28000})});
