"use client";
import { useMemo, useState } from "react";

type ClassName="Savaşçı"|"Büyücü"|"Şifacı";
type Item={id:number;name:string;family:string;className:ClassName;type:string;icon:string;color:string;ench:string[];image:string;set:string};
type SetDef={family:string;className:ClassName;set:string;weapon:string;image:string;body:string[];weaponStats:string[]};
const sets:SetDef[]=[
{family:"Bıçak Sırtı",className:"Savaşçı",set:"Maksimum Hasar Seti",weapon:"Kılıç",image:"https://i.hizliresim.com/nJ5R9g.jpg",body:["Maksimum Hasar: 600.000","Saldırı: 13.760","Kritik Vuruş: 4.354"],weaponStats:["Maksimum Hasar: 600.000","Saldırı: 27.520","Kritik Vuruş: 4.354"]},
{family:"Taş Kanat",className:"Savaşçı",set:"Tank Seti",weapon:"Balta",image:"",body:["Maksimum Enerji: 477.000","Savunma: 13.760","Kritik Zırhı: 8.000","Direnç (Hepsi): 32.000"],weaponStats:["Maksimum Enerji: 477.000","Savunma: 27.520","Kritik Zırhı: 8.000","Direnç (Hepsi): 32.000"]},
{family:"Hidra Nefesi",className:"Savaşçı",set:"Ateş Hasar Seti",weapon:"Çift Bıçak",image:"",body:["Hasar (Ateş): 300.000","Saldırı: 13.760","Kritik Vuruş: 4.354"],weaponStats:["Hasar (Ateş): 300.000","Saldırı: 27.520","Kritik Vuruş: 4.354"]},
{family:"Kıyamet",className:"Büyücü",set:"Büyü Fiziksel Seti",weapon:"Asa",image:"https://www.istanbuloyun.com/content/i/buyucufiziksel.png",body:["Büyü Hasarı (Fiziksel): 150.000","Maksimum Kudret: 220.000","Büyü Kritik: 4.354"],weaponStats:["Büyü Hasarı (Hepsi): 300.000","Büyü Hasarı (Fiziksel): 150.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]},
{family:"Sıfır Kelvin",className:"Büyücü",set:"Büyü Buz Seti",weapon:"Asa",image:"https://www.istanbuloyun.com/content/i/buyucubuz.png",body:["Büyü Hasarı (Buz): 150.000","Maksimum Kudret: 220.000","Büyü Kritik: 4.354"],weaponStats:["Büyü Hasarı (Hepsi): 300.000","Büyü Hasarı (Buz): 150.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]},
{family:"Transformatör",className:"Büyücü",set:"Büyü Elektrik Seti",weapon:"Asa",image:"https://www.istanbuloyun.com/content/i/buyucuelektrik.png",body:["Büyü Hasarı (Elektrik): 150.000","Maksimum Kudret: 220.000","Büyü Kritik: 4.354"],weaponStats:["Büyü Hasarı (Hepsi): 300.000","Büyü Hasarı (Elektrik): 150.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]},
{family:"Cehennem",className:"Büyücü",set:"Büyü Ateş Seti",weapon:"Asa",image:"https://www.istanbuloyun.com/content/i/buyucuates.png",body:["Büyü Hasarı (Ateş): 150.000","Maksimum Kudret: 220.000","Büyü Kritik: 4.354"],weaponStats:["Büyü Hasarı (Hepsi): 300.000","Büyü Hasarı (Ateş): 150.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]},
{family:"Ruh Döven",className:"Şifacı",set:"Maksimum Hasar Seti",weapon:"Asa",image:"https://www.istanbuloyun.com/content/i/sifaciMaxHasar.png",body:["Maksimum Hasar: 600.000","Saldırı: 13.760","Kritik Vuruş: 4.354"],weaponStats:["Maksimum Hasar: 600.000","Saldırı: 27.520","Kritik Vuruş: 4.354","Kudret Rejenerasyonu: 75.000"]},
{family:"Mevlana",className:"Şifacı",set:"İyileştirme Seti",weapon:"Asa",image:"https://www.istanbuloyun.com/content/i/sifaciIyilestirme.png",body:["İyileştirme Büyüleri: 224.000","Maksimum Kudret: 220.000","Büyü Kritik: 4.354"],weaponStats:["İyileştirme Büyüleri: 383.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]},
{family:"Hidroflorik",className:"Şifacı",set:"Büyü Asit Seti",weapon:"Asa",image:"https://www.istanbuloyun.com/content/i/sifacibuyuzehir.png",body:["Büyü Hasarı (Asit): 150.000","Maksimum Kudret: 220.000","Büyü Kritik: 4.354"],weaponStats:["Büyü Hasarı (Hepsi): 300.000","Büyü Hasarı (Asit): 150.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]},
{family:"Siyanür",className:"Şifacı",set:"Büyü Zehir Seti",weapon:"Asa",image:"https://www.istanbuloyun.com/content/i/sifacizehir.png",body:["Büyü Hasarı (Zehir): 150.000","Maksimum Kudret: 220.000","Büyü Kritik: 4.354"],weaponStats:["Büyü Hasarı (Hepsi): 300.000","Büyü Hasarı (Zehir): 150.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]}
];
const armorPieces=["Ceket","Pantolon","Eldiven","Ayakkabı","Zırh"];
const data:Item[]=sets.flatMap((s,setIndex)=>[...armorPieces,s.weapon].map((piece,pieceIndex)=>({id:setIndex*10+pieceIndex+1,name:`${s.family} ${piece}`,family:s.family,className:s.className,type:piece,icon:s.className==="Büyücü"?"✦":s.className==="Şifacı"?"◇":"◆",color:s.className==="Büyücü"?"violet":s.className==="Şifacı"?"teal":"ember",set:s.set,image:s.image,ench:piece===s.weapon?s.weaponStats:s.body})));
const filters=["Tümü","Savaşçı","Büyücü","Şifacı"] as const;

export default function Home(){
 const [query,setQuery]=useState("");const [filter,setFilter]=useState<(typeof filters)[number]>("Tümü");const [selected,setSelected]=useState<Item|null>(null);
 const shown=useMemo(()=>{const q=query.toLocaleLowerCase("tr-TR").trim();return data.filter(i=>(filter==="Tümü"||i.className===filter)&&(!q||[i.name,i.family,i.type,i.className,...i.ench].join(" ").toLocaleLowerCase("tr-TR").includes(q)))},[query,filter]);
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">İ</span><span><strong>İKV</strong><small>EŞYA REHBERİ</small></span></a><nav><a href="#items">Eşyalar</a><a href="#how">Nasıl çalışır?</a><span className="beta">ALFA</span></nav></header>
  <section className="intro" id="top"><div><p className="eyebrow">TOPLULUK DESTEKLİ İKV VERİTABANI</p><h1>Aradığın eşya,<br/><em>tek bakışta.</em></h1><p className="lead">Eşyanın görünüş ailesini, efsun varyantlarını ve nereden düştüğünü tek yerde keşfet.</p></div><div className="search-panel"><label htmlFor="search">EŞYA ARA</label><div className="searchbox"><span>⌕</span><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Örn. 49 balyoz, ateş..."/><kbd>ARA</kbd></div><p>İsim, eşya türü, sınıf veya efsunla arayabilirsin.</p></div></section>
  <section className="catalog" id="items"><div className="section-heading"><div><p className="eyebrow">ÇEMBERLİTAŞ KOLEKSİYONU</p><h2>3. kademe şaheser eşyalar</h2></div><span className="count">{shown.length} KAYIT</span></div><div className="filter-row">{filters.map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div>
  {shown.length?<div className="item-grid">{shown.map(i=><button className="item-card" key={i.id} onClick={()=>setSelected(i)}><div className={`item-art ${i.color}`} style={{height:175,maxHeight:175,overflow:"hidden",position:"relative"}}><span>{i.icon}</span>{i.image?<img loading="lazy" src={i.image} alt={`${i.family} set görseli`} style={{position:"absolute",inset:0,width:"100%",height:175,maxHeight:175,objectFit:"contain",objectPosition:"center",display:"block"}} onError={e=>{e.currentTarget.style.display="none"}}/>:<small>GÖRSEL ARANIYOR · ÖZELLİKLER MEVCUT</small>}</div><div className="item-body"><div className="meta"><span>{i.className}</span><span>3. KADEME</span></div><h3>{i.name}</h3><p>{i.set}</p><div className="tags">{i.ench.slice(0,2).map(x=><span key={x}>{x}</span>)}</div><div className="source verified"><i/> Kaynaklı kayıt</div></div><span className="arrow">↗</span></button>)}</div>:<div className="empty"><strong>Eşya bulunamadı.</strong><p>Arama kelimesini veya sınıfı değiştir.</p><button onClick={()=>{setQuery("");setFilter("Tümü")}}>Filtreleri temizle</button></div>}</section>
  <section className="how" id="how"><div><p className="eyebrow">GÖRÜNÜŞ ≠ EFSUN</p><h2>Aynı görünüş,<br/>farklı güçler.</h2></div><div className="steps"><article><b>01</b><h3>Görünüş ailesini bul</h3><p>Silah veya zırhın ortak modelini eşleştir.</p></article><article><b>02</b><h3>Efsununu karşılaştır</h3><p>Aynı görünüşü kullanan varyantları ayır.</p></article><article><b>03</b><h3>Kaynağa ulaş</h3><p>Doğrulanmış boss, yaratık, görev ya da reçeteyi gör.</p></article></div></section>
  <footer><span>İKV EŞYA REHBERİ · TOPLULUK PROJESİ</span><p>Veriler arşiv kaynaklarından derlenmiştir; oyun güncellemeleriyle değişebilir.</p></footer>
  {selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="detail" role="dialog" aria-modal="true"><button className="close" onClick={()=>setSelected(null)}>×</button><div className={`detail-art ${selected.color}`} style={{height:230,maxHeight:230,overflow:"hidden",position:"relative"}}><span>{selected.icon}</span>{selected.image?<img src={selected.image} alt={`${selected.family} set görseli`} style={{position:"absolute",inset:0,width:"100%",height:230,maxHeight:230,objectFit:"contain",background:"#171511",display:"block"}} onError={e=>{e.currentTarget.style.display="none"}}/>:<small>OYUN İÇİ GÖRSEL ARANIYOR · ÖZELLİKLER MEVCUT</small>}</div><p className="eyebrow">{selected.className} · 3. KADEME · {selected.type}</p><h2>{selected.name}</h2><p className="detail-note">{selected.family} ailesinin {selected.set.toLocaleLowerCase("tr-TR")} parçası.</p><h4>ÖZELLİKLER</h4><div className="enchant-list">{selected.ench.map(x=><span key={x}>✦ {x}</span>)}</div><h4>ELDE ETME YÖNTEMİ</h4><dl><div><dt>Bölge</dt><dd>Çemberlitaş</dd></div><div><dt>Kaynak</dt><dd>Çemberlitaş bossları</dd></div><div><dt>Alternatif</dt><dd>Bosslardan düşen reçeteyle üretim</dd></div></dl><div className="source-actions"><a className="source-link" href="https://istanbulkiyametvakti.fandom.com/tr/wiki/Anasayfa" target="_blank" rel="noreferrer">İKV Fandom Wiki ↗</a><a className="source-link secondary" href="https://www.maxigamerz.com/konu/istanbul-kiyamet-vakti-ikv-cemberlitas-saheserlerinin-recete-detaylari.240307/" target="_blank" rel="noreferrer">Reçete arşivi ↗</a></div><div className="warning verified-box">✓ Adlar ve özellikler İKV topluluk kaynaklarıyla eşleştirildi.</div></section></div>}
 </main>
}
