"use client";
import {useMemo,useState} from "react";
type C="Savaşçı"|"Büyücü"|"Şifacı";type S="Gözlük"|"Ceket"|"Eldiven"|"Pantolon"|"Ayakkabı"|"Yüzük"|"Kolye"|"Silah";type G="Fiziksel"|"Kritik"|"Şifa"|"Zehir"|"Asit"|"Buz"|"Elektrik"|"Ateş"|"Tank"|"Direnç"|"Gazap";
const recipe="https://www.maxigamerz.com/konu/istanbul-kiyamet-vakti-ikv-cemberlitas-saheserlerinin-recete-detaylari.240307/",tSource="https://www.maxigamerz.com/konu/istanbul-kiyamet-vakti-ikv-buyuk-hol-tilsimlari-rehberi.240285/";
const slots:S[]=["Gözlük","Ceket","Eldiven","Pantolon","Ayakkabı","Yüzük","Kolye","Silah"],goals:Record<C,G[]>={"Savaşçı":["Fiziksel","Kritik","Tank","Direnç"],"Büyücü":["Kritik","Buz","Elektrik","Ateş","Fiziksel"],"Şifacı":["Şifa","Asit","Zehir","Gazap","Kritik"]};
const families=[["Bıçak Sırtı","Savaşçı","Fiziksel","Kılıç","Maksimum Hasar",600000,"Saldırı",13760],["Sıfır Kelvin","Büyücü","Buz","Asa","Büyü Hasarı (Buz)",150000,"Maksimum Kudret",220000],["Transformatör","Büyücü","Elektrik","Asa","Büyü Hasarı (Elektrik)",150000,"Maksimum Kudret",220000],["Cehennem","Büyücü","Ateş","Asa","Büyü Hasarı (Ateş)",150000,"Maksimum Kudret",220000],["Ruh Döven","Şifacı","Fiziksel","Asa","Maksimum Hasar",600000,"Saldırı",13760]] as const;
const items=families.flatMap(f=>(["Ceket","Eldiven","Pantolon","Ayakkabı","Silah"] as S[]).map(slot=>({id:f[0]+slot,name:`${f[0]} ${slot==="Silah"?f[3]:slot}`,family:f[0],klass:f[1] as C,goal:f[2] as G,slot,stats:{[f[4]]:f[5],[f[6]]:slot==="Silah"&&f[1]==="Savaşçı"?27520:f[7],"Kritik":4354}})));
const talismans=[{id:"",name:"Tılsım seçilmedi",damage:0,crit:0},...[50,100,150].map((v,i)=>({id:`g1${i}`,name:`Gazap 1 (${["I","II","III"][i]})`,damage:v,crit:0})),...[50,100,150].map((v,i)=>({id:`g2${i}`,name:`Gazap 2 (${["I","II","III"][i]})`,damage:0,crit:v}))];
const fmt=(n:number)=>new Intl.NumberFormat("tr-TR").format(n),accent=(g:G)=>({"Fiziksel":"physical","Kritik":"critical","Şifa":"heal","Zehir":"poison","Asit":"acid","Buz":"ice","Elektrik":"electric","Ateş":"fire","Tank":"tank","Direnç":"resist","Gazap":"wrath"}[g]);
export default function Home(){const[k,setK]=useState<C>("Büyücü"),[goal,setGoal]=useState<G>("Buz"),[hybrid,setHybrid]=useState<G|"Yok">("Kritik"),[mode,setMode]=useState("PvE"),[region,setRegion]=useState("Çemberlitaş"),[rival,setRival]=useState("Rakip yok"),[tid,setTid]=useState(""),[q,setQ]=useState(""),[detail,setDetail]=useState<(typeof items)[number]|null>(null);
 const available=items.filter(i=>i.klass===k&&(i.goal===goal||goal==="Kritik")),family=available[0]?.family,equipped=Object.fromEntries(slots.map(s=>[s,available.find(i=>i.family===family&&i.slot===s)])) as Record<S,(typeof items)[number]|undefined>,tal=talismans.find(t=>t.id===tid)!;
 const totals=useMemo(()=>{const o:Record<string,number>={};Object.values(equipped).forEach(i=>i&&Object.entries(i.stats).forEach(([x,v])=>o[x]=(o[x]||0)+v));if(k==="Şifacı"&&tal.damage)Object.keys(o).forEach(x=>/Asit|Zehir|Maksimum/.test(x)&&(o[x]*=1+tal.damage/100));return o},[k,family,tid]);
 const share=()=>navigator.clipboard?.writeText(`${location.origin}?sinif=${k}&ana=${goal}&hibrit=${hybrid}&mod=${mode}&bolge=${region}&rakip=${rival}&tilsim=${tid}`);
 return <main><header><a href="#top"><b>İKV</b> EŞYA ARŞİVİ</a><nav><a href="#builder">Build oluştur</a><a href="#items">Eşyalar</a><a href="#sources">Kaynaklar</a><i>ALFA</i></nav></header>
 <section className="hero" id="top"><div><p className="eyebrow">DOĞRULANABİLİR TOPLULUK REHBERİ</p><h1>Teçhizatını<br/><em>kanıtla, kur, paylaş.</em></h1><p>İKV eşyalarını görünüşten efsuna, reçeteden build sinerjisine kadar tek doğrulama zincirinde incele.</p></div><aside><small>ARŞİV DURUMU · 22.08.2026</small><strong>{items.length}</strong><span>kaynaklı eşya kaydı</span><p>{families.length} doğrulanmış aile · 0 uydurma görsel</p></aside></section>
 <section className="builder" id="builder"><Title eyebrow="SEKİZ YUVALI BUILD OLUŞTURUCU" title="Karakter planı"><button onClick={share}>Paylaşım bağlantısını kopyala</button></Title><div className="builderbox"><div className="controls"><Field name="01 · Sınıf">{(["Savaşçı","Büyücü","Şifacı"] as C[]).map(x=><button className={k===x?"on":""} onClick={()=>{setK(x);setGoal(goals[x][0]);setHybrid("Yok");setTid("")}} key={x}>{x}</button>)}</Field><Field name="02 · Ana hedef">{goals[k].map(x=><button data-accent={accent(x)} className={goal===x?"on":""} onClick={()=>setGoal(x)} key={x}>{x}</button>)}</Field><Field name="03 · Hibrit hedef"><select value={hybrid} onChange={e=>setHybrid(e.target.value as G|"Yok")}><option>Yok</option>{goals[k].filter(x=>x!==goal).map(x=><option key={x}>{x}</option>)}</select></Field><Field name="04 · Oyun bağlamı"><select value={mode} onChange={e=>setMode(e.target.value)}>{["PvE","PvP","Farm","Grup Bölgesi"].map(x=><option key={x}>{x}</option>)}</select><select value={region} onChange={e=>setRegion(e.target.value)}>{["Çemberlitaş","Büyük Hol","Veri bekleniyor"].map(x=><option key={x}>{x}</option>)}</select><select value={rival} onChange={e=>setRival(e.target.value)}>{["Rakip yok","Savaşçı","Büyücü","Şifacı"].map(x=><option key={x}>{x}</option>)}</select></Field><Field name="05 · Tılsım"><select value={tid} onChange={e=>setTid(e.target.value)}>{talismans.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></Field></div>
 <div className="board" data-accent={accent(goal)}><div className="summary"><div><small>AKTİF PLAN</small><h3>{k} · {goal}{hybrid!=="Yok"?` + ${hybrid}`:""}</h3><p>{mode} · {region} · {rival}</p></div><b>{family?"KAYNAKLI DİZİLİM":"VERİ BEKLİYOR"}</b></div><div className="slots">{slots.map(s=>{const i=equipped[s];return <button className={i?"filled":""} onClick={()=>i&&setDetail(i)} key={s}><i>{s[0]}</i><span><small>{s}</small><b>{i?.name||"Veri / görsel doğrulanıyor"}</b></span><em>{i?"↗":"…"}</em></button>})}</div><div className="mechanics"><article><small>BUILD TOPLAMI</small>{Object.entries(totals).length?Object.entries(totals).map(([x,v])=><p key={x}><b>{x}</b>{fmt(Math.round(v))}</p>):<p>Doğrulanmış dizilim yok.</p>}</article><article><small>SEÇİLİ TILSIM</small><h4>{tal.name}</h4><p>{tal.damage?`Asit, zehir ve maksimum hasar etkilerine +%${tal.damage}`:tal.crit?`Gazaptan gelen kritik ihtimaline +%${tal.crit}`:"Hesaba tılsım etkisi eklenmedi."}</p><a href={tSource} target="_blank">Kaynağı aç ↗</a></article></div></div></div></section>
 <section className="catalog" id="items"><Title eyebrow="KAYNAKLI EŞYA KAYITLARI" title="Eşya rehberi"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Eşya, sınıf veya aile…"/></Title><div className="cards">{items.filter(i=>!q||(`${i.name} ${i.klass}`).toLocaleLowerCase("tr-TR").includes(q.toLocaleLowerCase("tr-TR"))).map(i=><button className="card" data-accent={accent(i.goal)} onClick={()=>setDetail(i)} key={i.id}><div className="art"><span>{i.slot[0]}</span><small>GÖRSEL DOĞRULANIYOR</small></div><div className="copy"><p>{i.klass} · {i.slot}<b>ŞAHESER</b></p><h3>{i.name}</h3><div className="tooltip">{Object.entries(i.stats).map(([x,v])=><span key={x}>◆ {x}: {fmt(v)}</span>)}</div><footer>● Kaynaklı · tek kaynak</footer></div></button>)}</div></section>
 <section className="sources" id="sources"><div><p className="eyebrow">DOĞRULAMA DEFTERİ</p><h2>Bilgi varsa kaynak,<br/>yoksa açık durum.</h2></div><div><Source title="Çemberlitaş reçete arşivi" url={recipe}>Şaheser adları, parça özellikleri, üretim malzemeleri ve boss/reçete bağlamı.</Source><Source title="Büyük Hol tılsım arşivi" url={tSource}>Gazap 1 ve Gazap 2 kademeleri ile yüzde etkileri build hesabına aktarıldı.</Source><article className="warn"><b>Çelişki / eksik veri</b><p>Arşivde bazı alanlar yineleniyor veya tutarsız. İkinci kaynak görülmeden genişletilmedi. Gözlük, yüzük ve kolye adları doğrulanana kadar boş tutuldu.</p></article></div></section>
 {detail&&<div className="modal" onMouseDown={e=>e.target===e.currentTarget&&setDetail(null)}><article><button className="close" onClick={()=>setDetail(null)}>×</button><div className="art"><span>{detail.slot[0]}</span><small>YANLIŞ GÖRSEL YERİNE DOĞRULAMA DURUMU</small></div><p className="eyebrow">{detail.klass} · {detail.slot} · ŞAHESER</p><h2>{detail.name}</h2><div className="tooltip big">{Object.entries(detail.stats).map(([x,v])=><span key={x}>◆ {x}: {fmt(v)}</span>)}</div><dl><div><dt>Görünüş ailesi</dt><dd>{detail.family}</dd></div><div><dt>Bölge</dt><dd>Çemberlitaş</dd></div><div><dt>Elde etme</dt><dd>Boss düşümü veya reçeteyle üretim</dd></div><div><dt>Doğrulama</dt><dd>Tek kaynak · 22.08.2026</dd></div></dl><a className="sourceLink" href={recipe} target="_blank">Bilgi kaynağını aç ↗</a></article></div>}</main>}
function Field(p:{name:string;children:React.ReactNode}){return <fieldset><legend>{p.name}</legend><div>{p.children}</div></fieldset>}function Title(p:{eyebrow:string;title:string;children:React.ReactNode}){return <div className="title"><div><p className="eyebrow">{p.eyebrow}</p><h2>{p.title}</h2></div>{p.children}</div>}function Source(p:{title:string;url:string;children:React.ReactNode}){return <article><b>{p.title}</b><p>{p.children}</p><a href={p.url} target="_blank">Kaynağı incele ↗</a></article>}
