"use client";
import { useMemo, useState } from "react";

type Item={id:number;name:string;family:string;className:"Savaşçı"|"Büyücü"|"Şifacı";type:string;icon:string;color:string;ench:string[];image:string;set:string};
const data:Item[]=[
{id:1,name:"Bıçak Sırtı Kılıç",family:"Bıçak Sırtı",className:"Savaşçı",type:"Kılıç",icon:"◆",color:"ember",set:"Maksimum Hasar Seti",image:"https://i.hizliresim.com/nJ5R9g.jpg",ench:["Maksimum Hasar: 600.000","Saldırı: 27.520","Kritik Vuruş: 4.354"]},
{id:2,name:"Taş Kanat Balta",family:"Taş Kanat",className:"Savaşçı",type:"Balta",icon:"◆",color:"ember",set:"Tank Seti",image:"",ench:["Maksimum Enerji: 477.000","Savunma: 27.520","Kritik Zırhı: 8.000","Direnç (Hepsi): 32.000"]},
{id:3,name:"Hidra Nefesi Çift Bıçak",family:"Hidra Nefesi",className:"Savaşçı",type:"Çift Bıçak",icon:"⬟",color:"ember",set:"Ateş Hasar Seti",image:"",ench:["Hasar (Ateş): 300.000","Saldırı: 27.520","Kritik Vuruş: 4.354"]},
{id:4,name:"Kıyamet Asa",family:"Kıyamet",className:"Büyücü",type:"Asa",icon:"✦",color:"violet",set:"Büyü Fiziksel Seti",image:"https://www.istanbuloyun.com/content/i/buyucufiziksel.png",ench:["Büyü Hasarı (Hepsi): 300.000","Büyü Hasarı (Fiziksel): 150.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]},
{id:5,name:"Sıfır Kelvin Asa",family:"Sıfır Kelvin",className:"Büyücü",type:"Asa",icon:"✦",color:"violet",set:"Büyü Buz Seti",image:"https://www.istanbuloyun.com/content/i/buyucubuz.png",ench:["Büyü Hasarı (Hepsi): 300.000","Büyü Hasarı (Buz): 150.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]},
{id:6,name:"Cehennem Asa",family:"Cehennem",className:"Büyücü",type:"Asa",icon:"◈",color:"violet",set:"Büyü Ateş Seti",image:"https://www.istanbuloyun.com/content/i/buyucuates.png",ench:["Büyü Hasarı (Hepsi): 300.000","Büyü Hasarı (Ateş): 150.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]},
{id:7,name:"Ruh Döven Asa",family:"Ruh Döven",className:"Şifacı",type:"Asa",icon:"◇",color:"teal",set:"Maksimum Hasar Seti",image:"https://www.istanbuloyun.com/content/i/sifaciMaxHasar.png",ench:["Maksimum Hasar: 600.000","Saldırı: 27.520","Kritik Vuruş: 4.354","Kudret Rejenerasyonu: 75.000"]},
{id:8,name:"Mevlana Asa",family:"Mevlana",className:"Şifacı",type:"Asa",icon:"◇",color:"teal",set:"İyileştirme Seti",image:"https://www.istanbuloyun.com/content/i/sifaciIyilestirme.png",ench:["İyileştirme Büyüleri: 383.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]},
{id:9,name:"Siyanür Asa",family:"Siyanür",className:"Şifacı",type:"Asa",icon:"⬢",color:"teal",set:"Büyü Zehir Seti",image:"https://www.istanbuloyun.com/content/i/sifacizehir.png",ench:["Büyü Hasarı (Hepsi): 300.000","Büyü Hasarı (Zehir): 150.000","Büyü Kritik: 4.354","Kudret Rejenerasyonu: 75.000"]}];
const filters=["Tümü","Savaşçı","Büyücü","Şifacı"] as const;

export default function Home(){
 const [query,setQuery]=useState("");const [filter,setFilter]=useState<(typeof filters)[number]>("Tümü");const [selected,setSelected]=useState<Item|null>(null);
 const shown=useMemo(()=>{const q=query.toLocaleLowerCase("tr-TR").trim();return data.filter(i=>(filter==="Tümü"||i.className===filter)&&(!q||[i.name,i.family,i.type,i.className,...i.ench].join(" ").toLocaleLowerCase("tr-TR").includes(q)))},[query,filter]);
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">İ</span><span><strong>İKV</strong><small>EŞYA REHBERİ</small></span></a><nav><a href="#items">Eşyalar</a><a href="#how">Nasıl çalışır?</a><span className="beta">ALFA</span></nav></header>
  <section className="intro" id="top"><div><p className="eyebrow">TOPLULUK DESTEKLİ İKV VERİTABANI</p><h1>Aradığın eşya,<br/><em>tek bakışta.</em></h1><p className="lead">Eşyanın görünüş ailesini, efsun varyantlarını ve nereden düştüğünü tek yerde keşfet.</p></div><div className="search-panel"><label htmlFor="search">EŞYA ARA</label><div className="searchbox"><span>⌕</span><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Örn. 49 balyoz, ateş..."/><kbd>ARA</kbd></div><p>İsim, eşya türü, sınıf veya efsunla arayabilirsin.</p></div></section>
  <section className="catalog" id="items"><div className="section-heading"><div><p className="eyebrow">ÇEMBERLİTAŞ KOLEKSİYONU</p><h2>3. kademe şaheser eşyalar</h2></div><span className="count">{shown.length} KAYIT</span></div><div className="filter-row">{filters.map(f=><button key={f} className={filter===f?"active":""} onClick={()=>setFilter(f)}>{f}</button>)}</div>
  {shown.length?<div className="item-grid">{shown.map(i=><button className="item-card" key={i.id} onClick={()=>setSelected(i)}><div className={`item-art ${i.color}`} style={{height:175,maxHeight:175,overflow:"hidden",position:"relative"}}><span>{i.icon}</span>{i.image?<img loading="lazy" src={i.image} alt={`${i.family} set görseli`} style={{position:"absolute",inset:0,width:"100%",height:175,maxHeight:175,objectFit:"cover",objectPosition:"center",display:"block"}} onError={e=>{e.currentTarget.style.display="none"}}/>:<small>GÖRSEL ARANIYOR</small>}</div><div className="item-body"><div className="meta"><span>{i.className}</span><span>3. KADEME</span></div><h3>{i.name}</h3><p>{i.set}</p><div className="tags">{i.ench.slice(0,2).map(x=><span key={x}>{x}</span>)}</div><div className="source verified"><i/> Kaynaklı kayıt</div></div><span className="arrow">↗</span></button>)}</div>:<div className="empty"><strong>Eşya bulunamadı.</strong><p>Arama kelimesini veya sınıfı değiştir.</p><button onClick={()=>{setQuery("");setFilter("Tümü")}}>Filtreleri temizle</button></div>}</section>
  <section className="how" id="how"><div><p className="eyebrow">GÖRÜNÜŞ ≠ EFSUN</p><h2>Aynı görünüş,<br/>farklı güçler.</h2></div><div className="steps"><article><b>01</b><h3>Görünüş ailesini bul</h3><p>Silah veya zırhın ortak modelini eşleştir.</p></article><article><b>02</b><h3>Efsununu karşılaştır</h3><p>Aynı görünüşü kullanan varyantları ayır.</p></article><article><b>03</b><h3>Kaynağa ulaş</h3><p>Doğrulanmış boss, yaratık, görev ya da reçeteyi gör.</p></article></div></section>
  <footer><span>İKV EŞYA REHBERİ · TOPLULUK PROJESİ</span><p>Veriler arşiv kaynaklarından derlenmiştir; oyun güncellemeleriyle değişebilir.</p></footer>
  {selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="detail" role="dialog" aria-modal="true"><button className="close" onClick={()=>setSelected(null)}>×</button><div className={`detail-art ${selected.color}`} style={{height:230,maxHeight:230,overflow:"hidden",position:"relative"}}><span>{selected.icon}</span>{selected.image?<img src={selected.image} alt={`${selected.family} set görseli`} style={{position:"absolute",inset:0,width:"100%",height:230,maxHeight:230,objectFit:"contain",background:"#171511",display:"block"}} onError={e=>{e.currentTarget.style.display="none"}}/>:<small>OYUN İÇİ GÖRSEL ARANIYOR</small>}</div><p className="eyebrow">{selected.className} · 3. KADEME · {selected.type}</p><h2>{selected.name}</h2><p className="detail-note">{selected.family} ailesinin {selected.set.toLocaleLowerCase("tr-TR")} parçası.</p><h4>ÖZELLİKLER</h4><div className="enchant-list">{selected.ench.map(x=><span key={x}>✦ {x}</span>)}</div><h4>ELDE ETME YÖNTEMİ</h4><dl><div><dt>Bölge</dt><dd>Çemberlitaş</dd></div><div><dt>Kaynak</dt><dd>Çemberlitaş bossları</dd></div><div><dt>Alternatif</dt><dd>Bosslardan düşen reçeteyle üretim</dd></div></dl><a className="source-link" href="https://www.maxigamerz.com/konu/istanbul-kiyamet-vakti-ikv-cemberlitas-saheserlerinin-recete-detaylari.240307/" target="_blank" rel="noreferrer">Kaynak sayfayı aç ↗</a><div className="warning verified-box">✓ Ad ve özellikler iki topluluk arşiviyle eşleştirildi.</div></section></div>}
 </main>
}
