export const SITE_RELEASE = {
  version: "0.68.1",
  channel: "BETA",
  milestone: "M68.1",
  releasedOn: "2026-08-29",
  releasedAt: "29 Ağustos 2026",
  title: "Güvenli Adet Onayı",
  summary:
    "Sarı etiketli adetler artık okuyucu tahminiyle otomatik stoka girmez; kullanıcı doğruladıktan sonra tüm üretim türlerinin azami adedi hesaplanır.",
  changes: [
    "Sarı adet etiketi bulunan her yığın güvenli moda alındı; hiçbir OCR sonucu kullanıcı doğrulaması olmadan stok veya üretim hesabına girmiyor.",
    "Okuyucunun bulduğu sayı kesin değer yerine düzenlenebilir adet önerisi olarak gösteriliyor.",
    "Etiketsiz tekli yuvalar 1 kalıyor; etiketli fakat okunamayan yuvalar boş ve zorunlu onaylı kalıyor.",
    "Yanlış adet onaylanmadan iksir, tılsım, eşya, silah ve ara malzeme üretim sonuçlarına taşınamıyor.",
    "Tarayıcının deneysel metin okuyucusu bulunmadığında sarı oyun içi adet etiketlerini cihaz içinde çözen yedek rakam okuyucu eklendi.",
    "Sarı adet etiketi bulunan bir yuva artık otomatik olarak 1 sayılmıyor; okunamayan veya düşük güvenli miktar açık onaya bırakılıyor.",
    "Fotoğraf taslağı iksir, tılsım, eşya, silah ve ara malzeme reçetelerinin tamamında aynı anda hesaplanıyor.",
    "Onay ekranında stoka işlemeden önce üretilebilir reçeteler ve her biri için azami üretim adedi gösteriliyor.",
    "Analiz aşaması, ilerleme yüzdesi ve geçen süre fotoğraf panelinde canlı gösteriliyor.",
    "Yoğun ikon karşılaştırması parçalara bölündü; mobil tarayıcı hesap sırasında arayüzü güncelleyebiliyor.",
    "Referans ikon imzaları sonraki fotoğraflarda yeniden kullanılmak üzere cihaz belleğinde önbelleğe alınıyor.",
    "18 saniyede tamamlanmayan işlem güvenli biçimde durduruluyor ve tekrar deneme sunuluyor.",
    "Makul düşük güvenli eşleşmeler aday olarak onay ekranına geliyor; isim onaylanmadan stok değişmiyor.",
    "Tarayıcı rakamı okuyamadığında adet artık sessizce 1 kabul edilmiyor; sarı miktar etiketi bulunan yuva boş bırakılıyor.",
    "Oyunda miktar etiketi görünmeyen tekli yuvalar 1 olarak ayrılıyor; etiketli fakat okunamayan yığınlar kullanıcı onayı bekliyor.",
    "Eksik adet tamamlanmadan fotoğraf taslağının stoka işlenmesi engelleniyor.",
    "Telefonla çekilmiş özgün 8×8 banka fotoğrafında parlak ikon kenarlarının sahte ızgara sayılması engellendi.",
    "Gri-ton kenar ritmi artık parlak renk çizgilerinden önce değerlendirilerek gerçek hücre sınırları seçiliyor.",
    "Eksik son sınır yalnız beklenen konumda yeterli kenar kanıtı varsa tamamlanıyor; zayıf hayalî dış sınırlar budanıyor.",
    "Yarım hücre kaydıran katalog hizalaması kaldırıldı; ikonlar doğrudan bulunan hücre sınırları içinde karşılaştırılıyor.",
    "Kamera parlaklığında runner-up'tan belirgin ayrılmayan benzer maden ve taş ikonları yanlış adla taslağa alınmıyor.",
    "Zayıf veya birbirine yakın ikon eşleşmeleri artık malzeme adı olarak onay taslağına alınmıyor.",
    "Adet okuyucu yalnız hücrenin sol üstündeki saf rakam alanını kabul ediyor; ikon ve araç ipucu rakamlarını dışarıda bırakıyor.",
    "Net ekran görüntülerindeki yumuşak, kesintili veya kısmen örtülü çanta çizgileri hücre ritmine göre de algılanıyor.",
    "Fotoğraf yüklenir yüklenmez çanta ızgarası ve doğrulanmış malzeme ikonları cihaz içinde otomatik karşılaştırılıyor.",
    "Tanınan malzeme ve adetler güven oranı, adet uyarısı ve düzenlenebilir onay listesiyle gösteriliyor.",
    "Manuel ikon kataloğu ana adım olmaktan çıkarıldı; yalnız eksik veya yanlış sonucu düzeltmek için açılıyor.",
    "Onaylanan stoktan en yakın üç ila beş eşya, tılsım veya iksir üretim adayı hesaplanıyor.",
  ],
} as const;
