import fs from "node:fs";
const read=name=>JSON.parse(fs.readFileSync(new URL("../data/"+name,import.meta.url),"utf8"));
const coreItems=read("items.json"),groupItems=read("group-loot-items.json"),glassesItems=read("glasses-items.json"),glassesStatGroups=read("glasses-stats.json"),groupEvidenceGroups=read("group-loot-evidence.json"),recipes=read("recipes.json"),sources=read("sources.json"),coreEvidence=read("evidence.json"),images=read("images.json"),talismans=read("talismans.json"),contexts=read("contexts.json"),enchants=read("enchants.json"),enchantSeries=read("enchant-series.json"),abilities=read("abilities.json");
const items=[...coreItems,...groupItems,...glassesItems],stats=[...read("stats.json"),...glassesStatGroups.flatMap(row=>row.stats.map(([attribute,value],index)=>({id:`stat-${row.itemId}-${index}`,itemId:row.itemId,attribute,value,unit:"puan",verificationStatus:"single_source",lastChecked:"2026-08-23"})))],evidence=[...coreEvidence,...groupEvidenceGroups.flatMap(group=>group.itemIds.flatMap(itemId=>["name","class","slot"].map(field=>({id:`ev-${itemId}-${field}`,itemId,field,sourceId:group.sourceId,locator:group.locator,status:"single_source",checkedAt:"2026-08-23"})))),...glassesItems.flatMap(item=>["name","class","level","slot"].map(field=>({id:`ev-${item.id}-${field}`,itemId:item.id,field,sourceId:"fandom-glasses",locator:"Gözlükler tablosu",status:"single_source",checkedAt:"2026-08-23"})))];
const errors=[], unique=(rows,label)=>{const ids=rows.map(x=>x.id);if(new Set(ids).size!==ids.length)errors.push(`${label}: yinelenen kimlik`)};
[["items",items],["stats",stats],["recipes",recipes],["sources",sources],["evidence",evidence],["talismans",talismans],["contexts",contexts],["enchants",enchants],["abilities",abilities]].forEach(([n,r])=>unique(r,n));
const itemIds=new Set(items.map(x=>x.id)),sourceIds=new Set(sources.map(x=>x.id));
const allowed={class:["Savaşçı","Büyücü","Şifacı","Tüm Sınıflar"],slot:["Gözlük","Ceket","Eldiven","Pantolon","Ayakkabı","Zırh","Amplifikatör","Yüzük","Kolye","Silah"],rarity:["Şaheser","Doğrulanmadı"],status:["draft","single_source","cross_verified","conflicted"],source:["official","forum","fandom","video","player_screenshot"]};
for(const i of items){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(i.id))errors.push(`${i.id}: kararlı slug değil`);for(const k of ["class","slot","rarity"])if(!allowed[k].includes(i[k]))errors.push(`${i.id}: geçersiz ${k}`);if(!allowed.status.includes(i.publicationStatus))errors.push(`${i.id}: geçersiz durum`)}
for(const s of sources)if(!allowed.source.includes(s.type)||!s.url||!s.accessedAt||!s.independenceGroup)errors.push(`${s.id}: eksik/geçersiz kaynak`);
for(const s of stats){if(!itemIds.has(s.itemId))errors.push(`${s.id}: kırık eşya`);if(!(s.value>0)||!s.unit)errors.push(`${s.id}: pozitif/birimli değil`)}
for(const r of recipes){if(!itemIds.has(r.itemId)||!sourceIds.has(r.sourceId))errors.push(`${r.id}: kırık referans`);if(!r.materials.length||r.materials.some(m=>!m.name||!(m.quantity>0)))errors.push(`${r.id}: geçersiz malzeme`)}
for(const e of evidence){if(!itemIds.has(e.itemId)||!sourceIds.has(e.sourceId))errors.push(`${e.id}: kırık kanıt`);if(e.status==="cross_verified"){const peers=evidence.filter(x=>x.itemId===e.itemId&&x.field===e.field&&x.status==="cross_verified");const groups=new Set(peers.map(x=>sources.find(s=>s.id===x.sourceId)?.independenceGroup));if(groups.size<2)errors.push(`${e.id}: bağımsız olmayan çapraz doğrulama`)}}
for(const i of items)for(const field of ["name","class","slot"])if(!evidence.some(e=>e.itemId===i.id&&e.field===field&&e.checkedAt&&sourceIds.has(e.sourceId)))errors.push(`${i.id}: ${field} için tarihli/kaynaklı kanıt yok`);
for(const image of images)if(!itemIds.has(image.itemId)||!sourceIds.has(image.sourceId)||!image.checkedAt||!image.nameAndAppearanceTogether)errors.push(`${image.id}: görsel kalite kapısı`);
for(const t of talismans){const validEffect=["damage_multiplier","critical_multiplier","stat_multiplier"].includes(t.effect),validTarget=t.effect!=="stat_multiplier"||(Array.isArray(t.targetAttributes)&&t.targetAttributes.length>0&&Boolean(t.outputAttribute));if(!sourceIds.has(t.sourceId)||!allowed.class.includes(t.class)||!t.color||![1,2,3].includes(t.tier)||!validEffect||!validTarget||!allowed.status.includes(t.status)||!t.lastChecked)errors.push(`${t.id}: eksik/geçersiz tılsım modeli`)}
for(const c of contexts)if(!sourceIds.has(c.sourceId)||!c.name||!c.type||!Array.isArray(c.bosses)||!Array.isArray(c.modes)||!allowed.status.includes(c.status)||!c.lastChecked)errors.push(`${c.id}: eksik/geçersiz bağlam modeli`);
for(const e of enchants)if(!sourceIds.has(e.sourceId)||!e.name||!e.attribute||!(e.value>0)||!e.unit||!allowed.status.includes(e.status)||!e.lastChecked)errors.push(`${e.id}: eksik/geçersiz efsun modeli`);
for(const series of enchantSeries)if(!series.id||!series.attribute||!series.unit||!Array.isArray(series.entries)||series.entries.some(entry=>!entry[0]||!(entry[1]>0)))errors.push(`${series.id}: eksik/geçersiz efsun serisi`);
for(const ability of abilities)if(!allowed.class.includes(ability.class)||!ability.name||![1,10,20,30,40].includes(ability.unlockLevel)||!Array.isArray(ability.roles)||!ability.roles.length||!sourceIds.has(ability.sourceId)||!allowed.status.includes(ability.status))errors.push(`${ability.id}: eksik/geçersiz yetenek modeli`);
if(coreItems.length<67)errors.push(`çekirdek Çemberlitaş denetimi 67 yerine ${coreItems.length} kayıt içeriyor`);
if(errors.length){console.error(errors.join("\n"));process.exit(1)}console.log(`Veri doğrulandı: ${items.length} eşya, ${stats.length} özellik, ${recipes.length} reçete, ${evidence.length} kanıt, ${talismans.length} tılsım, ${enchants.length+enchantSeries.flatMap(x=>x.entries).length} ham efsun satırı, ${abilities.length} yetenek.`);
