import fs from "node:fs";
const read=name=>JSON.parse(fs.readFileSync(new URL("../data/"+name,import.meta.url),"utf8"));
const coreItems=read("items.json"),groupItems=read("group-loot-items.json"),glassesItems=read("glasses-items.json"),glassesStatGroups=read("glasses-stats.json"),groupEvidenceGroups=read("group-loot-evidence.json"),cemberlitasEvidenceGroups=read("cemberlitas-evidence.json"),itemCrossEvidenceGroups=read("item-cross-evidence.json"),recipes=read("recipes.json"),sources=read("sources.json"),coreEvidence=read("evidence.json"),images=read("images.json"),appearanceImages=read("appearance-images.json"),appearanceQueue=read("appearance-media-queue.json"),visualFamilies=read("visual-families.json"),materialIcons=read("material-icons.json"),talismans=read("talismans.json"),talismanIcons=read("talisman-icons.json"),talismanRecipeAcquisitions=read("talisman-recipe-acquisition.json"),talismanProduction=read("talisman-production.json"),contexts=read("contexts.json"),enchants=read("enchants.json"),enchantSeries=read("enchant-series.json"),abilities=read("abilities.json"),abilityDetails=read("ability-details.json"),abilityVariants=read("ability-variants.json"),abilityMedia=read("ability-media.json"),issues=read("issues.json"),progressionGaps=read("progression-gaps.json"),serverUpdate=read("server-updates.json");
const expandedEvidence=(groups,suffix="")=>groups.flatMap(group=>group.itemIds.flatMap(itemId=>["name","class","slot"].map(field=>({id:`ev-${itemId}-${field}-${group.sourceId}${suffix}`,itemId,field,sourceId:group.sourceId,locator:group.locator,status:group.status,checkedAt:group.checkedAt}))));
const items=[...coreItems,...groupItems,...glassesItems],stats=[...read("stats.json"),...glassesStatGroups.flatMap(row=>row.stats.map(([attribute,value],index)=>({id:`stat-${row.itemId}-${index}`,itemId:row.itemId,attribute,value,unit:"puan",verificationStatus:"single_source",lastChecked:"2026-08-23"}))),...read("group-derived-stats.json")],evidence=[...coreEvidence,...expandedEvidence(cemberlitasEvidenceGroups,"-cross"),...expandedEvidence(itemCrossEvidenceGroups,"-cross"),...expandedEvidence(groupEvidenceGroups),...glassesItems.flatMap(item=>["name","class","level","slot"].map(field=>({id:`ev-${item.id}-${field}`,itemId:item.id,field,sourceId:"fandom-glasses",locator:"Gözlükler tablosu",status:"single_source",checkedAt:"2026-08-23"})))];
const errors=[], unique=(rows,label)=>{const ids=rows.map(x=>x.id);if(new Set(ids).size!==ids.length)errors.push(`${label}: yinelenen kimlik`)};
[["items",items],["stats",stats],["recipes",recipes],["sources",sources],["evidence",evidence],["images",images],["appearanceImages",appearanceImages],["appearanceQueue",appearanceQueue],["visualFamilies",visualFamilies],["materialIcons",materialIcons.map(row=>({...row,id:row.name}))],["talismans",talismans],["talismanVendors",talismanProduction.vendors],["contexts",contexts],["enchants",enchants],["abilities",abilities],["abilityDetails",abilityDetails.map(row=>({...row,id:row.abilityId}))],["abilityVariants",abilityVariants],["abilityMedia",abilityMedia],["issues",issues],["progressionGaps",progressionGaps]].forEach(([n,r])=>unique(r,n));
const itemIds=new Set(items.map(x=>x.id)),sourceIds=new Set(sources.map(x=>x.id));
const allowed={class:["Savaşçı","Büyücü","Şifacı","Tüm Sınıflar"],slot:["Gözlük","Ceket","Eldiven","Pantolon","Ayakkabı","Zırh","Amplifikatör","Yüzük","Kolye","Silah"],rarity:["Şaheser","Doğrulanmadı"],status:["draft","single_source","cross_verified","conflicted"],source:["official","server_guide","community_server_guide","community_server_news","community_server_live_data","forum","fandom","document","video","player_screenshot"]};
for(const i of items){if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(i.id))errors.push(`${i.id}: kararlı slug değil`);for(const k of ["class","slot","rarity"])if(!allowed[k].includes(i[k]))errors.push(`${i.id}: geçersiz ${k}`);if(!allowed.status.includes(i.publicationStatus))errors.push(`${i.id}: geçersiz durum`)}
for(const s of sources)if(!allowed.source.includes(s.type)||!s.url||!s.accessedAt||!s.independenceGroup)errors.push(`${s.id}: eksik/geçersiz kaynak`);
for(const s of stats){if(!itemIds.has(s.itemId))errors.push(`${s.id}: kırık eşya`);if(!(s.value>0)||!s.unit)errors.push(`${s.id}: pozitif/birimli değil`);if(s.sourceId&&!sourceIds.has(s.sourceId))errors.push(`${s.id}: kırık özellik kaynağı`)}
for(const r of recipes){if(!itemIds.has(r.itemId)||!sourceIds.has(r.sourceId))errors.push(`${r.id}: kırık referans`);if(!r.materials.length||r.materials.some(m=>!m.name||!(m.quantity>0)))errors.push(`${r.id}: geçersiz malzeme`)}
for(const e of evidence){if(!itemIds.has(e.itemId)||!sourceIds.has(e.sourceId))errors.push(`${e.id}: kırık kanıt`);if(e.status==="cross_verified"){const peers=evidence.filter(x=>x.itemId===e.itemId&&x.field===e.field&&x.status==="cross_verified");const groups=new Set(peers.map(x=>sources.find(s=>s.id===x.sourceId)?.independenceGroup));if(groups.size<2)errors.push(`${e.id}: bağımsız olmayan çapraz doğrulama`)}}
for(const i of items)for(const field of ["name","class","slot"])if(!evidence.some(e=>e.itemId===i.id&&e.field===field&&e.checkedAt&&sourceIds.has(e.sourceId)))errors.push(`${i.id}: ${field} için tarihli/kaynaklı kanıt yok`);
for(const image of images){const validScope=image.assetScope==="item_icon"||image.assetScope==="item_appearance",validCoverage=image.assetScope==="item_icon"?image.nameAndAppearanceTogether===false:image.nameAndAppearanceTogether===true;if(!itemIds.has(image.itemId)||!sourceIds.has(image.sourceId)||!image.url||!image.checkedAt||!validScope||!validCoverage)errors.push(`${image.id}: görsel kalite kapısı`)}
for(const icon of materialIcons)if(!icon.name||!icon.path?.startsWith("/materials/")||!sourceIds.has(icon.sourceId))errors.push(`${icon.name}: kırık malzeme ikonu kaynağı`);
const appearanceFamilyKeys=new Set(coreItems.filter(item=>item.class!=="Tüm Sınıflar"&&item.appearanceFamily).map(item=>`${item.class}|${item.appearanceFamily}`));
const queueFamilyKeys=new Set(appearanceQueue.map(row=>`${row.class}|${row.appearanceFamily}`));
for(const image of appearanceImages)if(!appearanceFamilyKeys.has(`${image.class}|${image.appearanceFamily}`)||!sourceIds.has(image.sourceId)||!image.url||!image.focus||!image.checkedAt||image.scope!=="set_appearance"||image.nameAndSetAppearanceTogether!==true)errors.push(`${image.id}: set görünüş kalite kapısı`);
for(const row of appearanceQueue)if(!appearanceFamilyKeys.has(`${row.class}|${row.appearanceFamily}`)||!row.sourcePage||!row.note||!["set_reference_only","awaiting_capture","page_pending"].includes(row.status))errors.push(`${row.id}: geçersiz görsel edinim kuyruğu`);
for(const key of appearanceFamilyKeys)if(!queueFamilyKeys.has(key))errors.push(`${key}: görsel edinim kuyruğunda yok`);
for(const key of queueFamilyKeys)if(!appearanceFamilyKeys.has(key))errors.push(`${key}: bilinmeyen görünüş ailesi kuyruğu`);
const visualScopes=["set_appearance","shared_item_type","shared_talisman_type","shared_potion_type"],visualStatuses=["verified","user_defined","awaiting_capture"],visualAssetIds=new Set([...images,...appearanceImages].map(row=>row.id).concat(talismanIcons.map(row=>row.path)));
for(const family of visualFamilies){
  if(!["item","talisman","potion"].includes(family.kind)||!visualScopes.includes(family.scope)||!visualStatuses.includes(family.status)||!family.label||!family.note)errors.push(`${family.id}: geçersiz görünüş ailesi`);
  if(family.assetRef&&!visualAssetIds.has(family.assetRef))errors.push(`${family.id}: kırık görünüş varlığı`);
  if(family.scope==="set_appearance"&&(!family.class||!family.appearanceFamily))errors.push(`${family.id}: eksik set eşlemesi`);
  if(family.scope==="shared_item_type"&&!(family.slots?.length||family.nameSuffixes?.length))errors.push(`${family.id}: eksik ortak eşya eşlemesi`);
  if(family.scope==="shared_talisman_type"&&(!allowed.class.slice(0,3).includes(family.class)||!['Kırmızı','Mavi'].includes(family.color)))errors.push(`${family.id}: geçersiz tılsım sınıf/renk eşlemesi`);
  if(family.scope==="shared_potion_type"&&(!['health','power','support'].includes(family.category)||!family.color||!family.sizeRule))errors.push(`${family.id}: geçersiz iksir görünüş kuralı`);
}
const itemVisualRows=visualFamilies.filter(row=>row.kind==="item"),visualFamilyForItem=item=>itemVisualRows.find(row=>row.scope==="set_appearance"&&row.class===item.class&&row.appearanceFamily===item.appearanceFamily)??itemVisualRows.find(row=>row.scope==="shared_item_type"&&((row.nameSuffixes??[]).some(suffix=>item.name.endsWith(suffix))||(row.slots??[]).includes(item.slot)));
for(const item of items)if(!visualFamilyForItem(item))errors.push(`${item.id}: görünüş ailesine bağlanmadı`);
if(new Set(items.map(item=>visualFamilyForItem(item)?.id)).size!==23)errors.push("eşya kataloğu 23 ortak görünüş ailesine ayrılmalı");
if(visualFamilies.filter(row=>row.scope==="shared_talisman_type").length!==6)errors.push("tılsımlar sınıf ve renge göre altı ortak görsel ailesine ayrılmalı");
if(visualFamilies.filter(row=>row.scope==="shared_potion_type").length!==3)errors.push("iksirler kırmızı, mavi ve turkuaz üç ortak görsel ailesine ayrılmalı");
for(const t of talismans){const validEffect=["damage_multiplier","critical_multiplier","stat_multiplier","informational"].includes(t.effect),validTarget=t.effect!=="stat_multiplier"||(Array.isArray(t.targetAttributes)&&t.targetAttributes.length>0&&Boolean(t.outputAttribute));if(!sourceIds.has(t.sourceId)||!allowed.class.includes(t.class)||!["Kırmızı","Mavi"].includes(t.color)||(t.tier!==null&&![1,2,3].includes(t.tier))||!t.effectText||!validEffect||!validTarget||!allowed.status.includes(t.status)||!t.lastChecked||(t.verificationSourceIds??[]).some(id=>!sourceIds.has(id)))errors.push(`${t.id}: eksik/geçersiz tılsım modeli`)}
const talismanKeys=new Set();
for(const t of talismans){const key=`${t.class}|${t.series}|${t.color}|${t.tier??"özel"}`;if(talismanKeys.has(key))errors.push(`${key}: yinelenen tılsım`);talismanKeys.add(key)}
for(const klass of ["Savaşçı","Büyücü","Şifacı"]){const classRows=talismans.filter(t=>t.class===klass);for(const color of ["Kırmızı","Mavi"])if(!classRows.some(t=>t.color===color))errors.push(`${klass}: ${color} tılsım yok`);const tiered=new Map();for(const t of classRows.filter(t=>t.tier!==null)){const key=`${t.series}|${t.color}`;tiered.set(key,[...(tiered.get(key)??[]),t.tier])}for(const [series,tiers] of tiered)if([...new Set(tiers)].sort().join(",")!=="1,2,3")errors.push(`${klass} ${series}: I-II-III serisi eksik`) }
if(talismanProduction.tierRules.length!==4||new Set(talismanProduction.tierRules.map(rule=>String(rule.tier))).size!==4)errors.push("tılsım üretim kuralları dört benzersiz kademeyi kapsamalı");
for(const rule of talismanProduction.tierRules)if(!rule.label||!rule.acquisition||typeof rule.recipeRequired!=="boolean"||!["awaiting_verification","source_matched"].includes(rule.materialsStatus)||!rule.note||!Array.isArray(rule.sourceIds)||!rule.sourceIds.length||rule.sourceIds.some(id=>!sourceIds.has(id)))errors.push(`${rule.tier}: geçersiz tılsım üretim kuralı`);
for(const vendor of talismanProduction.vendors)if(!vendor.name||!vendor.kind||!vendor.region||!vendor.role||!Array.isArray(vendor.namedOffers)||!vendor.namedOffers.length||vendor.namedOffers.some(name=>!talismans.some(talisman=>talisman.name===name))||!vendor.scopeNote||vendor.serverScope!=="normal_ikv"||!sourceIds.has(vendor.sourceId)||vendor.status!=="single_source"||!vendor.lastChecked)errors.push(`${vendor.id}: geçersiz tılsım satıcısı`);
for(const reference of talismanProduction.serverReferences??[])if(reference.server!=="Kıyametin Öncüleri"||!reference.claim||!reference.scopeNote||!sourceIds.has(reference.sourceId)||reference.status!=="single_source"||!reference.lastChecked)errors.push(`${reference.id}: geçersiz KÖ tılsım referansı`);
for(const report of talismanProduction.playerReports??[])if(report.server!=="Kıyametin Öncüleri"||!Array.isArray(report.talismanIds)||!report.talismanIds.length||report.talismanIds.some(id=>!talismans.some(talisman=>talisman.id===id&&talisman.tier===1))||report.itemKind!=="Hazır tılsım"||!report.claim||!report.npc||(report.price!==null&&!(report.price>0))||!report.priceLabel||report.status!=="needs_verification"||!report.evidenceNeeded||!report.reportedAt)errors.push(`${report.id}: geçersiz oyuncu bildirimi`);
for(const acquisition of talismanRecipeAcquisitions)if(!Array.isArray(acquisition.talismanIds)||!acquisition.talismanIds.length||acquisition.talismanIds.some(id=>!talismans.some(talisman=>talisman.id===id))||acquisition.serverScope!=="normal_ikv"||!["exact","ambiguous_name"].includes(acquisition.status)||!acquisition.method||!acquisition.location||!acquisition.detail||!sourceIds.has(acquisition.sourceId)||!acquisition.lastChecked)errors.push(`${acquisition.id}: geçersiz reçete edinim kaydı`);
const exactAcquisitionIds=new Set(talismanRecipeAcquisitions.filter(row=>row.status==="exact").flatMap(row=>row.talismanIds));
if(exactAcquisitionIds.size!==13||talismanRecipeAcquisitions.filter(row=>row.status==="ambiguous_name").length!==2)errors.push("tılsım reçete edinimi 13 kesin kimlik ve 2 ad-çakışmalı kaydı korumalı");
for(const c of contexts)if(!sourceIds.has(c.sourceId)||!c.name||!c.type||!Array.isArray(c.bosses)||!Array.isArray(c.modes)||!allowed.status.includes(c.status)||!c.lastChecked)errors.push(`${c.id}: eksik/geçersiz bağlam modeli`);
for(const e of enchants)if(!sourceIds.has(e.sourceId)||!e.name||!e.attribute||!(e.value>0)||!e.unit||!allowed.status.includes(e.status)||!e.lastChecked)errors.push(`${e.id}: eksik/geçersiz efsun modeli`);
for(const series of enchantSeries)if(!series.id||!series.attribute||!series.unit||!Array.isArray(series.entries)||series.entries.some(entry=>!entry[0]||!(entry[1]>0)))errors.push(`${series.id}: eksik/geçersiz efsun serisi`);
for(const ability of abilities)if(!allowed.class.includes(ability.class)||!ability.name||![1,10,20,30,40].includes(ability.unlockLevel)||!Array.isArray(ability.roles)||!ability.roles.length||!sourceIds.has(ability.sourceId)||!allowed.status.includes(ability.status))errors.push(`${ability.id}: eksik/geçersiz yetenek modeli`);
for(const klass of ["Savaşçı","Büyücü","Şifacı"])for(const level of [1,10,20,30,40])if(abilities.filter(ability=>ability.class===klass&&ability.unlockLevel===level).length!==3)errors.push(`${klass} ${level}: üç temel yetenek bekleniyor`);
const abilityIds=new Set(abilities.map(ability=>ability.id));
for(const detail of abilityDetails){
  const sourceGroups=new Set([detail.sourceId,...(detail.verificationSourceIds??[])].map(id=>sources.find(source=>source.id===id)?.independenceGroup));
  if(!abilityIds.has(detail.abilityId)||!detail.target||!detail.effect||!detail.duration||!detail.cooldown||!Array.isArray(detail.progression)||!detail.progression.length||!sourceIds.has(detail.sourceId)||(detail.verificationSourceIds??[]).some(id=>!sourceIds.has(id))||!detail.evidenceImage?.startsWith("/evidence/")||!allowed.status.includes(detail.status)||!detail.lastChecked)errors.push(`${detail.abilityId}: eksik/geçersiz yetenek ayrıntısı`);
  if(detail.status==="cross_verified"&&sourceGroups.size<2)errors.push(`${detail.abilityId}: bağımsız olmayan yetenek doğrulaması`);
}
for(const variant of abilityVariants){
  const sourceGroups=new Set([variant.sourceId,...(variant.verificationSourceIds??[])].map(id=>sources.find(source=>source.id===id)?.independenceGroup));
  if(!allowed.class.includes(variant.class)||!variant.name||!abilityIds.has(variant.replacesAbilityId)||variant.usesSamePoints!==true||!variant.target||!variant.effect||!variant.duration||!variant.cooldown||!Array.isArray(variant.progression)||!variant.progression.length||!sourceIds.has(variant.sourceId)||(variant.verificationSourceIds??[]).some(id=>!sourceIds.has(id))||!variant.evidenceImage?.startsWith("/evidence/")||!allowed.status.includes(variant.status)||!variant.lastChecked)errors.push(`${variant.id}: eksik/geçersiz yetenek varyantı`);
  if(variant.status==="cross_verified"&&sourceGroups.size<2)errors.push(`${variant.id}: bağımsız olmayan varyant doğrulaması`);
}
const mediaStatuses=["awaiting_capture","single_source","cross_verified","conflicted"];
for(const media of abilityMedia){
  if(!abilityIds.has(media.abilityId)||!mediaStatuses.includes(media.status)||!Array.isArray(media.sources)||!Array.isArray(media.sourceIds))errors.push(`${media.id}: eksik/geçersiz yetenek medyası`);
  if(media.sources.some(source=>!source.src||!["video/webm","video/mp4"].includes(source.type)))errors.push(`${media.id}: geçersiz video kaynağı`);
  if(media.audio&&(!media.audio.src||!String(media.audio.type).startsWith("audio/")))errors.push(`${media.id}: geçersiz ses kaynağı`);
  if(media.sourceIds.some(sourceId=>!sourceIds.has(sourceId)))errors.push(`${media.id}: kırık medya kaynağı`);
  if(media.status==="awaiting_capture"&&(media.poster||media.sources.length||media.audio||media.sourceIds.length))errors.push(`${media.id}: bekleyen medya boş olmalı`);
  if(media.status!=="awaiting_capture"&&(!media.sources.length||!media.sourceIds.length||!media.checkedAt))errors.push(`${media.id}: yayımlanan medya kanıtsız`);
}
for(const issue of issues){
  const required=["title","shortTitle","priority","category","area","evidenceStatus","observation","impact","inference","quickFix","midTermFix","longTermFix","metric"];
  if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(issue.id)||required.some(field=>!issue[field])||!["P0","P1","P2"].includes(issue.priority)||!Array.isArray(issue.reproduction)||issue.reproduction.length<3||!Array.isArray(issue.sourceIds)||issue.sourceIds.some(id=>!sourceIds.has(id)))errors.push(`${issue.id}: eksik/geçersiz sorun modeli`);
}
for(const gap of progressionGaps){
  const validObservations=Array.isArray(gap.observations)&&gap.observations.length>=3&&gap.observations.every(row=>row.label&&row.detail&&["community","public","market","warning","conflict"].includes(row.level));
  if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(gap.id)||!Number.isInteger(gap.step)||!gap.label||!["P0","P1","P2"].includes(gap.priority)||!["evidence_needed","single_video","community_report","market_verified","conflicted","release_pending"].includes(gap.status)||!gap.statusLabel||!gap.lastChecked||!gap.why||!gap.known||!validObservations||!Array.isArray(gap.safeActions)||gap.safeActions.length<2||!Array.isArray(gap.unknown)||gap.unknown.length<4||!Array.isArray(gap.evidenceNeeded)||gap.evidenceNeeded.length<3)errors.push(`${gap.id}: eksik/geçersiz ilerleme açığı`);
}
if(progressionGaps.map(row=>row.step).join(",")!=="1,2,3,4,5,6")errors.push("ilerleme açıkları kullanıcı sırasını korumalı");
const serverSectionIds=["pvp","anka","mining","regions","connection","update-warning"];
if(!serverUpdate.id||!serverUpdate.title||!serverUpdate.publishedAt||serverUpdate.verificationStatus!=="single_source"||!serverUpdate.scopeNote||serverUpdate.sections.map(row=>row.id).join(",")!==serverSectionIds.join(","))errors.push("30 Ağustos sunucu güncellemesi eksik/geçersiz");
for(const section of serverUpdate.sections)if(!section.title||!["reported_fixed","conflicted","temporary_notice"].includes(section.status)||!Array.isArray(section.items)||!section.items.length)errors.push(`${section.id}: geçersiz sunucu güncelleme bölümü`);
const miningUpdate=serverUpdate.sections.find(row=>row.id==="mining");
if(miningUpdate?.status!=="conflicted"||!miningUpdate.conflict?.earlier||!miningUpdate.conflict?.later||!miningUpdate.conflict?.decision)errors.push("maden güncellemesi çelişki kaydını korumalı");
if(coreItems.length<67)errors.push(`çekirdek Çemberlitaş denetimi 67 yerine ${coreItems.length} kayıt içeriyor`);
if(errors.length){console.error(errors.join("\n"));process.exit(1)}console.log(`Veri doğrulandı: ${items.length} eşya, ${stats.length} özellik, ${recipes.length} reçete, ${evidence.length} kanıt, ${images.length} tekil eşya görseli, ${appearanceImages.length} set görünüş referansı, ${visualFamilies.length} ortak görünüş kuralı, ${appearanceQueue.length} ailelik görsel kuyruğu, ${talismans.length} tılsım, ${talismanProduction.vendors.length} tılsım satıcısı, ${enchants.length+enchantSeries.flatMap(x=>x.entries).length} ham efsun satırı, ${abilities.length} temel yetenek, ${abilityDetails.length} oyun içi yetenek ayrıntısı, ${abilityVariants.length} varyant, ${abilityMedia.length} medya pilotu, ${issues.length} sorun kaydı, ${progressionGaps.length} ilerleme açığı, 1 sunucu güncellemesi.`);
